### ISSUE TITLE
Cornucopia and "Gandharan-cornucopia"

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#10]
This is a matter we need to discuss: 

1. cornucopia (the container of the Graeco-Roman tradition) 
2. "Gandharan cornucopia" (similar to the former, but featuring an animal-shaped end - generally that of a caprid). 

The "cornucopia" often appears on small statues and is perhaps a simplified rendering of the "Gandharan cornucopia". 

See A.A. Di Castro 2015 [https://www.academia.edu/12204182/Goat_Heads_and_Goddesses_in_Sw%C4%81t_Gandh%C4%81ra_and_Kashmir_and_Connected_Problems](url)

**Comment by cristiano-moscatelli** [comment]
A possible Sanskrit term for "cornucopia" is _prapuṭa_ (to be checked) 

https://sanskrit.inria.fr/MW/169.html

**Comment by jessiepons** [comment]
Ask Peter about the sautoir necklace
+ prapuṭa

**Comment by jessiepons** [comment]
The response regarding praputa & the transliteration system are:

1.	Could “prapuṭa” translate as cornucopia, or horn of plenty and be used to refer to the attribute carried by Ceres or Fortuna (or in the Gandharan context, Hariti).
1. Hummm, I'm not sure. Why do you want to know? Where have you found it? I don't know this word. It occurs in the Kauśikasūtra, I don't see it recorded anywhere else though I guess you've found it somewhere. I see Bloomfield translates it as "a large cornucopia" but he gives no justification for this. puṭa- means 'pocket' or similar, and is itself of unknown etymology. I'd be very wary of adopting Bloomfield's translation, but if it suits your context you should certainly cite it.

2.	To which transliteration system would Avalokiteshvara (instead of IAST’s Avalokiteśvara) or praputa (instead of IAST’s prapuṭa) or lakshana (instead of lākṣaṇa) correspond? It’s not Harvard-Tokyo or Veltuis which uses the capitalized letters or the “.n”. So how would that weird hybrid system be called?
2. Do you mean this system doesn't transliterate long vowels or retroflexes etc.? Gosh, sorry I don't know! Are you sure it's even a system?

**Comment by SerenaAutiero** [comment]
@jessiepons @cristiano-moscatelli I would leave praputa out, if this is ok for you we can close this issue.

As for transliteration we can add it as "simple transliteration" and insert a table somewhere, what do you think?

**Comment by jessiepons** [comment]
I agree with leaving prapuṭa out. We don't want to use Indic terminology at all costs.

Yes, something like "simplified transliteration" would work I guess.

**Comment by cristiano-moscatelli** [comment]
agree on both
