### ISSUE TITLE
New Concept: [śākya]

### ISSUE THREAD

**Issue by InbarMaor** [DiGArtefacts/thesaurus#147]
Please search <https://w3id.org/diga/terms> first and check if a corresponding concept already exists.

Please provide some information about the concept you want to suggest.

**śākya**
Give the concept a main label in English.

--Following Roy's suggestion in one of the meetings. We would like to tag the appearances of this word. --

**Alternative labels**
List additional labels. Specify the language if not English. (Currently, the thesaurus supports English, Italian, and Sanskrit.)

**Suggested broader concepts**
Specify an appropriate (existing) parent concept from the thesaurus.

**External IDs**
Suggest matching external IDs in vocabularies like Getty AAT or ONAMA that the new concept should link to.

**Comment by jessiepons** [comment]
I can add a concept śākya (uri: 2082004976). In order to place it correctly in the ontology, I would need to know the context in which it appears. 

As a refer to the śākya clan or as an epiteth of the Buddha?

Spontaneously, I would place it under "literary persons" => "human beings". But I could also add is as an alternative label to Sakhyamuni.
