### ISSUE TITLE
Add "joist" [architectural element] (and chaitya arch?)

### ISSUE THREAD

**Issue by cristiano-moscatelli** [DiGArtefacts/thesaurus#20]
The Repertorio lacks the term for these rectangular/square-ended elements projecting from the intrados of arches. These should be the joists (IT: "travetto" or "travicello"). 

Plus, the arch in question is the chaitya arch (gavākṣha). Should we add it to the Thesaurus?

<img width="361" alt="Schermata 2022-07-17 alle 21 43 42" src="https://user-images.githubusercontent.com/108815325/179422701-8fc5696f-9cff-41c6-af37-5aa9c30c819c.png">

**Comment by SerenaAutiero** [comment]
Please check page 85 of the Repertorio, I actually did not add chaitya arch before because it would correspond to more than one Repertorio type, we could create a further upper level in the hierarchy and group the variants illustrated in the repertorio all under the same parent. 

As for adding "joist", would it make sense to add another arch type as "Voluted raised round arch with carinated extrados and joists in the intrados" or "chaitya arch with joists and pendants"?

**Comment by SerenaAutiero** [comment]
voluted raised round arch with carinated extrados and joists in the intrados --> https://w3id.org/diga/terms/1214100279

"chaitya arch" as a concept is not feasible since it reduces the repertoire to mostly a Western/Indian divide, considering as "western" the plain round arch

**Comment by cristiano-moscatelli** [comment]
From Percy:

these are called purlins or liernes (valaya in Sanskrit). They are traverse beams interconnecting the semi-circular rafters (lupā) of the barrel vaults.

**Comment by SerenaAutiero** [comment]
changed 'joists' into 'purlins' in https://w3id.org/diga/terms/1214100279
